title: "Mediumish"
description: "Jekyll template, Medium styled, free for bloggers."
baseurl: "/medium"
url: "https://ovidiuchis.github.io"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
google_analytics: ""
disqus: ""
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

paginate: 6
paginate_path: /page:num/

authors:
  ovidiu:
    name: Ovidiu CHIS
    display_name: Ovidiu CHIS
    email: contact@ovidiuchis.ro
    web: https://ovidiuchis.github.io
    twitter: https://twitter.com/ovidiuchis
    avatar: "assets/images/avatar.png" # poți adăuga o imagine proprie aici
    description: "Consultant ERP, pasionat de Scriptură, tehnologie și ucenicie digitală."
sass:
  sass_dir: _sass
theme: null

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

adsense: "disabled"
lazyimages: "disabled"
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
