name: Build Medium Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          cd medium-src
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build blog with Jekyll (explicit)
        run: |
          cd medium-src
          bundle exec jekyll build --config _config.yml --destination ../medium
