name: Build Medium Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          cd medium-src
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build blog with Jekyll
        run: |
          cd medium-src
          bundle exec jekyll build --destination ../medium

      - name: Commit and push medium folder to main branch
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add medium
          git commit -m "Update /medium blog build" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/ovidiuchis/ovidiuchis.github.io.git HEAD:main
